/**
 * Created by 橘 on 2017/5/7.
 */
(function(){
    'use strict';

// Declare app level module which depends on views, and components
    angular.module('xjszrs', [
        "ui.router",'toaster',"ngAnimate","ngCookies","ngStorage","ngResource"
    ]).
    config(['$stateProvider', '$locationProvider', '$urlRouterProvider','$httpProvider','$urlMatcherFactoryProvider',
        function($stateProvider,$locationProvider,$urlRouterProvider,$httpProvider,$urlMatcherFactoryProvider) {//路由定义
            $urlRouterProvider.otherwise('/regist');
            $stateProvider
                .state('regist', {
                    url: '/regist',
                    templateUrl: 'views/regist.html',
                    controller:"registController"
                })
                .state('regsuccess', {
                    url: '/regsuccess',
                    templateUrl: 'views/success.html'
                })
            ;
    }])
    ;
})();
(function () {
    'use strict';
    angular.module('xjszrs').run(['$rootScope', '$log',"wechatService","$location","runmodal","AuthServerProvider",
        function($rootScope, $log,wechatService,$location,runmodal,AuthServerProvider){
            $rootScope.isloading=true;
            console.log("do login start...")
            AuthServerProvider.login({
                username: "admin",
                password: "admin123!",
                rememberMe: true
            },function(){
                console.log("do login finish...")
                //启动
                wechatService.wechatConfig();
                if(runmodal=="dev"){//调试模式模拟身份
                    wechatService.testUser();
                }else{
                    var url=$location.$$absUrl;
                    var pos=url.indexOf("code=");
                    if(pos>0){
                        url=url.substring(pos+5);
                        console.log(url);
                        var nextPos=url.indexOf("&");
                        var code=url.substring(0,nextPos);
                        console.log(code);
                        console.log("system start! find code param.invoke code user method");
                        wechatService.loadWechatUser(code);
                    }

                }
            });

    }]);

})();
(function () {
    'use strict';
    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE
    angular
        .module('xjszrs')
        .constant('smsurl', "http://test.moistmedia.net/activityserver/api/sendsms")
        // .constant('tokenUrl', "http://localhost:8082/api/authenticate/client")
        // .constant('domain',"http://localhost:8082/")
        // .constant('rootpath',"http://localhost:8082/activitywechat/")
        .constant('tokenUrl', "http://test.moistmedia.net/activityserver/api/authenticate/client")
        .constant('domain',"http://test.moistmedia.net/activityserver/")
        .constant('rootpath',"http://test.moistmedia.net/activitywechat/")
        .constant('homePage',"regist")
        .constant('wechatappid',"wx83f372e021582278")
        .constant('runmodal',"prod")
    ;
})();
